const blogData = [
  {
    title: "Top 10 Jewelry Trends You Must Know",
    slug: "top-10-jewelry-trends",
    excerpt: "Latest jewelry trends that are dominating the market.",
    content: "This blog explains the top jewelry trends including minimalist gold pieces, gemstone designs and handcrafted items.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762339504/pexels-umutdagli-28856506_w2crto.jpg",
    tags: ["jewelry", "fashion", "trends"],
    category: "Jewelry",
    productCategory: "Necklace",
    metaTitle: "Top Jewelry Trends",
    metaDescription: "Discover the top 10 jewelry trends of the year.",
    keywords: ["jewelry", "trends", "fashion"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "How to Choose the Perfect Engagement Ring",
    slug: "choose-perfect-engagement-ring",
    excerpt: "A complete guide to choosing an engagement ring.",
    content: "Learn how to select a ring based on diamond type, clarity, metal, and design preferences.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762339501/pexels-dhanno-20593518_uyvx3u.jpg",
    tags: ["engagement", "rings", "guide"],
    category: "Jewelry",
    productCategory: "Ring",
    metaTitle: "Perfect Engagement Ring",
    metaDescription: "Step-by-step guide to choosing the right engagement ring.",
    keywords: ["engagement ring", "diamond ring"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "Why Gold Jewelry is Always in Trend",
    slug: "why-gold-jewelry-in-trend",
    excerpt: "Gold jewelry has been trending forever.",
    content: "Gold jewelry is durable, timeless and always fashionable.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762339500/pexels-dhanno-28771729_zo4utx.jpg",
    tags: ["gold", "jewelry"],
    category: "Jewelry",
    productCategory: "Gold",
    metaTitle: "Gold Jewelry Trend",
    metaDescription: "Why gold jewelry never goes out of fashion.",
    keywords: ["gold", "jewelry"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "Difference Between 18k and 22k Gold",
    slug: "difference-between-18k-22k-gold",
    excerpt: "18k vs 22k gold – which one to choose?",
    content: "18k is more durable while 22k is more pure. Know which to choose based on usage.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762339501/pexels-rajeshverma-7791457_xyeocf.jpg",
    tags: ["gold", "karat", "guide"],
    category: "Jewelry",
    productCategory: "Gold",
    metaTitle: "18k vs 22k Gold",
    metaDescription: "Learn the difference between 18k and 22k gold.",
    keywords: ["18k gold", "22k gold"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "Best Necklace Designs for Weddings",
    slug: "best-necklace-designs-weddings",
    excerpt: "Stunning necklace designs for brides.",
    content: "Here are the trending necklace designs perfect for wedding events.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762339501/pexels-artworkbyumair-15226351_rssn3j.jpg",
    tags: ["necklace", "wedding", "jewelry"],
    category: "Jewelry",
    productCategory: "Necklace",
    metaTitle: "Wedding Necklace Designs",
    metaDescription: "Best necklace designs for brides and weddings.",
    keywords: ["necklace", "bridal jewelry"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "How to Take Care of Silver Jewelry",
    slug: "how-to-take-care-of-silver-jewelry",
    excerpt: "Simple silver jewelry care tips.",
    content: "Clean silver jewelry with mild soap, avoid chemicals and store in dry places.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762339500/pexels-dhanno-28771729_zo4utx.jpg",
    tags: ["silver", "care", "cleaning"],
    category: "Jewelry",
    productCategory: "Silver",
    metaTitle: "Silver Jewelry Care",
    metaDescription: "Tips to keep silver jewelry shiny and long-lasting.",
    keywords: ["silver jewelry", "care"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "Top 5 Handmade Jewelry Designs",
    slug: "top-5-handmade-jewelry-designs",
    excerpt: "Beautiful handmade jewelry ideas.",
    content: "Handmade jewelry designs include bead necklaces, wire-wrap pendants and handcrafted earrings.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762339501/pexels-thelazyartist-1415145_k7rm4x.jpg",
    tags: ["handmade", "craft", "jewelry"],
    category: "Jewelry",
    productCategory: "Handmade",
    metaTitle: "Handmade Jewelry",
    metaDescription: "Explore the top handmade jewelry design ideas.",
    keywords: ["handmade jewelry", "craft"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "Which Earrings Suit Your Face Shape?",
    slug: "earrings-for-face-shape",
    excerpt: "Choose earrings based on face shape.",
    content: "Round, oval, heart and square face shapes each suit different earrings.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762319842/fingerring1_n08xw7.jpg",
    tags: ["earrings", "fashion"],
    category: "Jewelry",
    productCategory: "Earrings",
    metaTitle: "Earrings for Face Shape",
    metaDescription: "Best earrings for each face shape.",
    keywords: ["earrings", "face shape"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "Top Gemstones You Should Know About",
    slug: "top-gemstones-you-should-know",
    excerpt: "Popular gemstones and their meanings.",
    content: "Emerald, ruby, sapphire and opal are the most demanded gemstones in jewelry.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762319800/necklece_yiutka.jpg",
    tags: ["gemstone", "jewelry"],
    category: "Jewelry",
    productCategory: "Gemstone",
    metaTitle: "Top Gemstones",
    metaDescription: "List of top gemstones and their uses.",
    keywords: ["gemstone", "jewelry"],
    likes: [],
    comments: [],
    viewsCount: 0
  },
  {
    title: "How to Style Bracelet with Any Outfit",
    slug: "style-bracelet-any-outfit",
    excerpt: "Bracelet styling tips.",
    content: "Minimalist, layered and charm bracelets work with casual and party outfits.",
    featuredImage: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762319800/brcelete7_txyjh0.jpg",
    tags: ["bracelet", "fashion"],
    category: "Jewelry",
    productCategory: "Bracelet",
    metaTitle: "Bracelet Styling",
    metaDescription: "How to match bracelet with your outfit.",
    keywords: ["bracelet", "style"],
    likes: [],
    comments: [],
    viewsCount: 0
  }
]


module.exports = blogData